sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile~!"
  - docker build -t rnrn99/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rnrn99/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "jiyu-docker-test"
  env: "Jiyudockertest-env"
  bucket_name: "jiyu-docker-test"
  bucket_path: "jiyu-docker-test"
  on:
    branch: main
